export const CHECKED_SQUARE = 'CHECKED_SQUARE';
export const CHECKED_EMPTY_SQUARE = 'CHECKED_EMPTY_SQUARE';
export const TOGGLE_FLAG = 'TOGGLE_FLAG';
export const SET_VISIBLE_BOARD = 'SET_VISIBLE_BOARD';
export const RESET_GAME = 'RESET_GAME';
